version: "3.8"

services:
  token:
    build: token/
    ports:
    - "8081:8080"

  users:
    build: users/
    ports:
    - "8082:8080"

  redis:
    env_file:
      - ".env"
    image: "redis:5.0.4-stretch"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "redis:/data"



volumes:
  redis: {}

