version: "3.8"

services:
  token:
    build: token/
    ports:
    - "8082:8080"
    depends_on:
        - "redis"

  users:
    build: users/
    ports:
    - "8081:8080"

  redis:
    env_file:
      - ".env"
    image: "redis:5.0.4-stretch"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - "redis:/data"

  database: 
    image: "postgres" # use latest official postgres version 
    env_file: 
        - database.env # configure postgres 
    volumes: 
        - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down


volumes:
  redis: {}
  database-data: # named volumes can be managed easier using docker-compose

